-- Players and Coaches Tables
-- Matching OOTP CSV export files: players.csv, coaches.csv

-- Players table (from players.csv)
CREATE TABLE IF NOT EXISTS players (
    player_id INTEGER PRIMARY KEY,
    team_id INTEGER,
    league_id INTEGER,
    position SMALLINT,
    role SMALLINT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    nick_name VARCHAR(50),
    age SMALLINT,
    date_of_birth DATE,
    city_of_birth_id INTEGER,
    nation_id INTEGER,
    second_nation_id INTEGER,
    weight SMALLINT,
    height SMALLINT,
    retired SMALLINT,
    free_agent SMALLINT,
    last_league_id INTEGER,
    last_team_id INTEGER,
    organization_id INTEGER,
    last_organization_id INTEGER,
    language_ids_0 INTEGER,
    language_ids_1 INTEGER,
    uniform_number SMALLINT,
    experience SMALLINT,
    person_type SMALLINT,
    bats SMALLINT,
    throws SMALLINT,
    personality_greed SMALLINT,
    personality_loyalty SMALLINT,
    personality_play_for_winner SMALLINT,
    personality_work_ethic SMALLINT,
    personality_intelligence SMALLINT,
    personality_leader SMALLINT,
    historical_id VARCHAR(50),
    historical_team_id VARCHAR(50),
    best_contract_offer_id INTEGER,
    injury_is_injured SMALLINT,
    injury_dtd_injury SMALLINT,
    injury_career_ending SMALLINT,
    injury_dl_left SMALLINT,
    injury_dl_playoff_round SMALLINT,
    injury_left SMALLINT,
    dtd_injury_effect SMALLINT,
    injury_id INTEGER,
    prone_overall SMALLINT,
    prone_leg SMALLINT,
    prone_back SMALLINT,
    prone_arm SMALLINT,
    fatigue_pitches_0 SMALLINT,
    fatigue_pitches_1 SMALLINT,
    fatigue_pitches_2 SMALLINT,
    fatigue_pitches_3 SMALLINT,
    fatigue_pitches_4 SMALLINT,
    fatigue_pitches_5 SMALLINT,
    fatigue_points SMALLINT,
    fatigue_played_today SMALLINT,
    running_ratings_speed SMALLINT,
    running_ratings_stealing SMALLINT,
    running_ratings_baserunning SMALLINT,
    college SMALLINT,
    draft_year SMALLINT,
    draft_round SMALLINT,
    draft_supplemental SMALLINT,
    draft_pick SMALLINT,
    draft_overall_pick SMALLINT,
    draft_eligible SMALLINT,
    hidden SMALLINT,
    draft_league_id INTEGER,
    draft_team_id INTEGER,
    turned_coach SMALLINT,
    hall_of_fame SMALLINT,
    rust SMALLINT,
    inducted SMALLINT,
    strategy_override_team SMALLINT,
    strategy_stealing INTEGER,
    strategy_running INTEGER,
    strategy_bunt_for_hit INTEGER,
    strategy_sac_bunt INTEGER,
    strategy_hit_run INTEGER,
    strategy_hook_start INTEGER,
    strategy_hook_relief INTEGER,
    strategy_pitch_count INTEGER,
    strategy_pitch_around INTEGER,
    strategy_no_pinch_if_rested SMALLINT,
    strategy_never_pinch_hit SMALLINT,
    strategy_defensive_sub SMALLINT,
    strategy_dtd_sit_min SMALLINT,
    strategy_dtd_allow_ph SMALLINT,
    local_pop SMALLINT,
    national_pop SMALLINT,
    draft_protected SMALLINT,
    morale SMALLINT,
    morale_player_performance SMALLINT,
    morale_team_performance SMALLINT,
    morale_team_transactions SMALLINT,
    expectation SMALLINT,
    morale_player_role SMALLINT,
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (league_id) REFERENCES leagues(league_id),
    FOREIGN KEY (city_of_birth_id) REFERENCES cities(city_id),
    FOREIGN KEY (nation_id) REFERENCES nations(nation_id),
    FOREIGN KEY (second_nation_id) REFERENCES nations(nation_id)
);

-- Coaches table (from coaches.csv)
CREATE TABLE IF NOT EXISTS coaches (
    coach_id INTEGER PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    nick_name VARCHAR(50),
    age SMALLINT,
    date_of_birth DATE,
    city_of_birth_id INTEGER,
    nation_id INTEGER,
    weight SMALLINT,
    height SMALLINT,
    position SMALLINT,
    experience SMALLINT,
    occupation SMALLINT,
    team_id INTEGER,
    former_player_id INTEGER,
    quick_left INTEGER,
    contract_salary INTEGER,
    contract_years INTEGER,
    contract_extension_salary INTEGER,
    contract_extension_years INTEGER,
    scout_major INTEGER,
    scout_minor INTEGER,
    scout_international INTEGER,
    scout_amateur INTEGER,
    scout_amateur_preference INTEGER,
    teach_hitting INTEGER,
    teach_pitching INTEGER,
    teach_fielding INTEGER,
    handle_veterans INTEGER,
    handle_rookies INTEGER,
    handle_players INTEGER,
    strategy_knowledge INTEGER,
    heal_legs INTEGER,
    heal_arms INTEGER,
    heal_back INTEGER,
    heal_other INTEGER,
    heal_rest INTEGER,
    management_style INTEGER,
    personality INTEGER,
    hitting_focus INTEGER,
    pitching_focus INTEGER,
    training_focus INTEGER,
    teach_running INTEGER,
    prevent_legs INTEGER,
    prevent_arms INTEGER,
    prevent_back INTEGER,
    prevent_other INTEGER,
    stealing INTEGER,
    running INTEGER,
    pinchrun INTEGER,
    pinchhit_pos INTEGER,
    pinchhit_pitch INTEGER,
    hook_start INTEGER,
    hook_relief INTEGER,
    closer INTEGER,
    lr_matchup INTEGER,
    bunt_hit INTEGER,
    bunt INTEGER,
    hit_run INTEGER,
    run_hit INTEGER,
    squeeze INTEGER,
    pitch_around INTEGER,
    intentional_walk INTEGER,
    hold_runner INTEGER,
    guard_lines INTEGER,
    infield_in INTEGER,
    outfield_in INTEGER,
    corners_in INTEGER,
    shift_if INTEGER,
    shift_of INTEGER,
    opener INTEGER,
    num_pitchers INTEGER,
    num_hitters INTEGER,
    favor_speed_to_power INTEGER,
    favor_avg_to_obp INTEGER,
    favor_defense_to_offense INTEGER,
    favor_pitching_to_hitting INTEGER,
    favor_veterans_to_prospects INTEGER,
    trade_aggressiveness INTEGER,
    player_loyalty INTEGER,
    trade_frequency INTEGER,
    trade_preference INTEGER,
    value_stats INTEGER,
    value_this_year INTEGER,
    value_last_year INTEGER,
    value_two_years INTEGER,
    draft_value INTEGER,
    intl_fa_value INTEGER,
    develop_value INTEGER,
    ratings_value INTEGER,
    manager_value INTEGER,
    pitching_coach_value INTEGER,
    hitting_coach_value INTEGER,
    scout_value INTEGER,
    doctor_value INTEGER,
    busy INTEGER,
    type INTEGER,
    data INTEGER,
    days_left INTEGER,
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (city_of_birth_id) REFERENCES cities(city_id),
    FOREIGN KEY (nation_id) REFERENCES nations(nation_id),
    FOREIGN KEY (former_player_id) REFERENCES players(player_id)
);

-- Player images (for both players and coaches)
CREATE TABLE IF NOT EXISTS person_images (
    person_id INTEGER,
    person_type VARCHAR(10), -- 'player' or 'coach'
    image_filename VARCHAR(255),
    image_path VARCHAR(500),
    file_size INTEGER,
    season_year INTEGER DEFAULT NULL,
    last_updated DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (person_id, person_type)
);

-- Branch family tracking (special table for our storyline)
CREATE TABLE IF NOT EXISTS branch_family_members (
    person_id INTEGER,
    person_type VARCHAR(10), -- 'player' or 'coach'
    relationship_type VARCHAR(50) NOT NULL, -- 'direct', 'spouse', 'in-law', 'adopted', etc.
    generation INTEGER, -- 1st generation, 2nd, etc.
    branch_line VARCHAR(50), -- Which family branch
    relationship_notes TEXT,
    added_date DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (person_id, person_type)
);

-- Players roster status (from players_roster_status.csv)
CREATE TABLE IF NOT EXISTS players_roster_status (
    player_id INTEGER PRIMARY KEY,
    team_id INTEGER,
    league_id INTEGER,
    position INTEGER,
    role INTEGER,
    uniform_number INTEGER,
    playing_level INTEGER,
    is_active INTEGER,
    is_on_secondary INTEGER,
    is_on_dl INTEGER,
    is_on_dl60 INTEGER,
    must_be_active INTEGER,
    just_signed INTEGER,
    was_on_active INTEGER,
    was_on_secondary INTEGER,
    was_on_dl INTEGER,
    mlb_service_years INTEGER,
    secondary_service_years INTEGER,
    pro_service_years INTEGER,
    mlb_service_days INTEGER,
    secondary_service_days INTEGER,
    pro_service_days INTEGER,
    mlb_service_days_this_year INTEGER,
    secondary_service_days_this_year INTEGER,
    pro_service_days_this_year INTEGER,
    dl_days_this_year INTEGER,
    years_protected_from_rule_5 INTEGER,
    is_on_waivers INTEGER,
    designated_for_assignment INTEGER,
    irrevocable_waivers INTEGER,
    days_on_waivers INTEGER,
    days_on_waivers_left INTEGER,
    days_on_dfa_left INTEGER,
    claimed_team_id INTEGER,
    last_day_on_waivers INTEGER,
    options_used INTEGER,
    option_used_this_year INTEGER,
    has_received_arbitration INTEGER,
    was_traded INTEGER,
    trade_status INTEGER,
    FOREIGN KEY (player_id) REFERENCES players(player_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (league_id) REFERENCES leagues(league_id)
);

-- Players contract (from players_contract.csv)
CREATE TABLE IF NOT EXISTS players_contract (
    player_id INTEGER PRIMARY KEY,
    team_id INTEGER,
    league_id INTEGER,
    position INTEGER,
    role INTEGER,
    is_major INTEGER,
    no_trade INTEGER,
    last_year_team_option INTEGER,
    last_year_player_option INTEGER,
    last_year_vesting_option INTEGER,
    next_last_year_team_option INTEGER,
    next_last_year_player_option INTEGER,
    next_last_year_vesting_option INTEGER,
    contract_team_id INTEGER,
    contract_league_id INTEGER,
    season_year INTEGER,
    salary_0 INTEGER,
    salary_1 INTEGER,
    salary_2 INTEGER,
    salary_3 INTEGER,
    salary_4 INTEGER,
    salary_5 INTEGER,
    salary_6 INTEGER,
    salary_7 INTEGER,
    salary_8 INTEGER,
    salary_9 INTEGER,
    years INTEGER,
    current_year INTEGER,
    minimum_pa INTEGER,
    minimum_pa_bonus INTEGER,
    minimum_ip INTEGER,
    minimum_ip_bonus INTEGER,
    mvp_bonus INTEGER,
    cyyoung_bonus INTEGER,
    allstar_bonus INTEGER,
    next_last_year_option_buyout INTEGER,
    last_year_option_buyout INTEGER,
    FOREIGN KEY (player_id) REFERENCES players(player_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (league_id) REFERENCES leagues(league_id)
);